#port
#server:
#  port: 80

# mariaDB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/joo
    username: joohyung
    password: joo123
    #test-whileIdle: true
    #validationQuery: select 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      #ddl-auto: create-drop
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
  #jackson:
    #serialization:
      #write_dates_as_timestamps: false  #json localdatetime format

file:
  upload:
    dir: /data/upload

login:
  isCheckState: false

# custom security config
jwt:
  header: Authorization
redirect:
  domain: http://localhost:3000

security:
  token:
    secret: wngudWkdWkd
    expiration: 86400 #토큰 유효기간, 단위 초(86400 -> 1일)


#log4j
logging:
  level:
    com.joo.web.controller.common.ControllerExceptionHandler: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.client.RestTemplate: TRACE
    org.springframework.web: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.type: trace
    org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoTokenServices: DEBUG
    org.springframework.security.web: DEBUG