version: '3.1'

services:

  db:
    container_name: app_db
    image: mariadb
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joo321
      MYSQL_DATABASE: joo
      MYSQL_USER: joohyung
      MYSQL_PASSWORD: joo123
    ports:
      - 3306:3306
#    volumes:
#      - ~/docker/mysql:/var/lib/mysql
# version 2.x
#    ports:
#      - 4001:3306
#    healthcheck:
#    #        test: "/usr/bin/mysql --user=root --password=joo321 --execute \"SHOW DATABASES;\""
#    #        interval: 2s
#    #        timeout: 20s
#    #        retries: 10
#
